version: "3.8"

networks:
  web:
    external: true
  internal:
    external: false
services:

  bottle-todo:
    build: .
    restart: always
    ports:
      - 5001:5000
    volumes:
      - .:/app
    labels:
      - traefik.http.routers.apiantony.rule=Host(`todo.labfp.es`)
      - traefik.http.routers.apiantony.tls=true
      - traefik.http.routers.apiantony.tls.certresolver=lets-encrypt
      - traefik.port=5001
    networks:
      - internal
      - web